baseURL = "https://stephenajulu.com"
languageCode = "en-us"
paginate = 6
title = "Stephen Ajulu's Personal Website, Blog and Portfolio"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "Notes"
url = "#notes"
weight = 7
[[menu.main]]
name = "Brands"
url = "#brands"
weight = 8
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 9


# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Latest Articles"
url = "blog"
weight = 2


[params]
blogPageURL = "blog"
notesPageURL = "notes"
brandsPageURL = "brands"
contactLink = "contact"
copyright = "All right reserved copyright © Stephen Ajulu 2021"
footerLogo = "images/favicon.png"
formspreeURL = "https://formspree.io/f/alunje73@gmail.com"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/favicon.png"
description = "Stephen Ajulu's Personal Website where you can find his portfolio, contacts and articles"
featureImage = ["images/featureImage.jpg"]
image = ["images/featureImage.jpg"]
images = ["images/featureImage.jpg"]


[params.address]
address = "Nairobi, Kenya"
email = "alunje73@gmail.com"
openingHours = "Contact me from 6am to 7pm (5pm Sundays Only)"
phone = "+254 726 024 210"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/stephenajulu"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/stephenajulu"
weight = 2
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/stephenajulu"
weight = 3
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/stephenajulu"
weight = 4
[[params.social]]
icon = "fa-youtube-square"
url = "https://www.youtube.com/channel/UC043ZXL-t3yqtgcIxJmkHuA"
weight = 5

[author]
    name = "Stephen Ajulu"
    email = "alunje73@gmail.com"
    twitter = "@stephenajulu"
    facebook = "stephenajulu"
