baseURL = "https://stephenajulu.com"
languageCode = "en-us"
paginate = 6
theme = ""
title = "Stephen Ajulu - Tech Consultant & Expert Based in Nairobi, Kenya"
[author]
email = "alunje73@gmail.com"
facebook = "stephenajulu"
name = "Stephen Ajulu"
twitter = "@stephenajulu"
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 8
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Latest Articles"
url = "https://ajulusthoughts.stephenajulu.com"
weight = 2
[params]
blogPageURL = ""
contactLink = "contact"
copyright = "© Stephen Ajulu  2015 - Today  "
description = "Stephen Ajulu's Personal Website where you can find his portfolio, contacts and articles"
featureImage = ["images/featureImage.jpg"]
footerLogo = "/images/stephen-ajulu-signature-white-slim-4.png"
formspreeURL = "https://formspree.io/f/alunje73@gmail.com"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
image = ["images/featureImage.jpg"]
images = ["images/featureImage.jpg"]
logo = "/images/stephen-ajulu-signature-black-slim-4.png"
notesPageURL = "notes"
[params.address]
address = "Nairobi, Kenya"
email = "alunje73@gmail.com"
openingHours = "Contact me anytime between 8am to 6pm(5pm Sundays) Eastern Time +03:00"
phone = "+254 726 024 210"
[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/stephenajulu"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/stephenajulu"
weight = 2
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/stephenajulu"
weight = 3
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/stephenajulu"
weight = 4
[[params.social]]
icon = "fa-youtube-square"
url = "https://www.youtube.com/channel/UC043ZXL-t3yqtgcIxJmkHuA"
weight = 5
